export INSTALL_ROOT=$ACTHOME/opt
export PATH=$INSTALL_ROOT/bin:$PATH
export LIBRARY_PATH=$INSTALL_ROOT/lib64:$INSTALL_ROOT/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$INSTALL_ROOT/lib64:$INSTALL_ROOT/lib:$LD_LIBRARY_PATH
