#! /bin/sh
#
# gcc_env.sh
#
# Copyright © 2017 Hongkun Yu <staryhk@gmail.com>
#
# @AUTHOR:      Hongkun Yu
# @MAIL:        staryhk@gmail.com
# @VERSION:     2017-01-21
#


#gcc
export GCC49_ROOT=/usr/local/Cellar/gcc@4.9/4.9.4_1
export PATH=$GCC49_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$GCC49_ROOT/lib:$LD_LIBRARY_PATH

#mpicc
export MPI_ROOT=/usr/local/Cellar/mpich-gcc/4.8
export PATH=$MPI_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$MPI_ROOT/lib:$LD_LIBRARY_PATH
