#! /bin/sh
#
# palias.sh
#
# Copyright © 2017 Hongkun Yu <staryhk@gmail.com>
#
# @AUTHOR:      Hongkun Yu
# @MAIL:        staryhk@gmail.com
# @VERSION:     2018-09-05
#


alias subl="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
alias setproxy="export https_proxy=http://127.0.0.1:7890 && export http_proxy=http://127.0.0.1:7890"
alias unsetproxy="unset https_proxy && unset http_proxy"
alias ipshow="curl cip.cc"
