#! /bin/sh
#
# palias.sh
#
# Copyright © 2017 Hongkun Yu <staryhk@gmail.com>
#
# @AUTHOR:      Hongkun Yu
# @MAIL:        staryhk@gmail.com
# @VERSION:     2018-09-05
#


alias subl="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
alias setproxy="export ALL_PROXY=socks5://127.0.0.1:1080"
alias unsetproxy="unset ALL_PROXY"
alias ipshow="curl -i https://ip.cn"
